server:
  port: 8000

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/db
    username: root
    password: root-password
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
  flyway:
    enabled: true
    validateMigrationNaming: true
    baseline-version: 1
    baselineOnMigrate: true

#logging:
#  level:
#    org:
#      hibernate:
#        SQL: DEBUG
#        type:
#          descriptor:
#            sql:
#              BasicBinder: TRACE

---
spring:
  config:
    activate:
      on-profile: test
  datasource:
    url: jdbc:h2:mem:test
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: update
