server:
  port: 8000

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/db
    username: root
    password: root-password
    driver-class-name: com.mysql.cj.jdbc.Driver
  flyway:
    enabled: true
    baseline-version: 1.0.0-001
    baselineOnMigrate: true

---
spring:
  config:
    activate:
      on-profile: test
  datasource:
    url: jdbc:h2:mem:test
    driver-class-name: org.h2.Driver
